apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "krypt-webapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "krypt-webapp.fullname" . }}
                port:
                  number: {{ .Values.service.port }}

