apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "krypt-smart-contract.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx-{{ .Release.Namespace }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /smart-contract
            pathType: Prefix
            backend:
              service:
                name: {{ include "krypt-smart-contract.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
